# SITE CONFIGURATION
title: B3C - Boozing Bitching Book Club # your site title
author: xoxo B3C # You :P
description: > # Meta description of Homepage
  Welcome to Boozing Bitching Book Club, the podcast that is Drunk History meets Book Club. 
  This is a biweekly podcast where we rotate between classic chic lit and all forms of other reading materials that women actually read! 
  The twist is that everyone has to bring booze that they feel connects to the story or how it made them personally feel, and they have to finish their drink by the time we stop recording.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://b3cpod.com" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Boozing Bitching Book Club
  links:
    - https://twitter.com/b3cpod
    - https://www.facebook.com/b3cpod/
    - https://www.instagram.com/b3cpod/
    - http://goodreads.com/b3cpod

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  100% realness with hints of sass

hero_img: posts/B3C-sans-logos.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: b3cpod@gmail.com # email for form submission

twitter_username: b3cpod # replace with your_twitter_username or comment to remove link from footer
#github_username:  janczizikow # replace with your_github_username or comment to remove link from footer
instagram_username: b3cpod # replace with your_instagram_username or comment to remove link from footer
facebook_username: b3cpod
goodreads_username: b3cpod

#disqus:
 # shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
